### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ranganathanm** [cisco/libest#70]
I get the following error when trying to compile after configure. What flags should I use to get over this? Thanks

est_client.c:3663:23: error: dereferencing pointer to incomplete type ‘X509_STORE {aka struct x509_store_st}’
     if (store && store->objs && sk_X509_OBJECT_num(store->objs) > 0) {

**Comment by ranganathanm** [comment]
It compiles with openssl 1.0.2 (says so somewhere in the documentation).

**Comment by rpb5bnc** [comment]
I suspect what's happening is that libest is being built against a
    1.1.x release of OpenSSL (either 1.1.0 or 1.1.1).  Things have
    changed in the API to OpenSSL between the 1.1.x releases and
    everything previous.  At this point, this version of libest is coded
    to OpenSSL 1.0.2.  If time permits, we'll be uplifting this
    implementation to 1.1.1 sometime this year since support for 1.0.2
    ends at the end of 2019.
    
    I would suggest building against OpenSSL 1.0.2 to get around this
    build error. 
    
    Hope this helps,
    Pete
    
    On 4/3/19 6:17 PM, M. Ranganathan
      wrote:
    
    
      
      I get the following error when trying to compile after
        configure. What flags should I use to get over this? Thanks
      est_client.c:3663:23: error: dereferencing pointer to
        incomplete type ‘X509_STORE {aka struct x509_store_st}’
        if (store && store->objs &&
        sk_X509_OBJECT_num(store->objs) > 0) {
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cisco/libest","title":"cisco/libest","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cisco/libest"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Compile error (#70)"}],"action":{"name":"View Issue","url":"https://github.com/cisco/libest/issues/70"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cisco/libest/issues/70",
"url": "https://github.com/cisco/libest/issues/70",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
